# Generated by Django 6.0.2 on 2026-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_extern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad_litros', models.CharField(max_length=100, verbose_name='Cantidad (Litros)')),
                ('saldo_tanque', models.CharField(max_length=100, verbose_name='Saldo en tanque (Litros)')),
                ('autorizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
