# Generated by Django 6.0.2 on 2026-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_extern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ente_propietario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ente propietario')),
                ('cantidad_ingreso_litros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de ingreso (Litros)')),
                ('cantidad_salida_litros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de salida (Litros)')),
                ('motivo_uso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de uso')),
                ('autorizado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorizado por')),
                ('rec_entr_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recibido/Entregado por')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
