# Generated by Django 6.0.2 on 2026-05-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers_extern', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='register_extern',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_externos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
