# Generated by Django 6.0.2 on 2026-03-17 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'max_length': 'Máximo 5 caracteres.', 'required': 'Este campo es requerido.'}, max_length=5, validators=[django.core.validators.RegexValidator('\\d', inverse_match=True, message='No se permiten números.')])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
