"""
Este archivo es la configuración para pytest en un proyecto Django. Aquí se
especifica el módulo de configuración de Django, los patrones de nombres de los
archivos de prueba y una opción para reutilizar la base de datos entre pruebas.
"""
[pytest]
DJANGO_SETTINGS_MODULE = Django_6_crud.settings
python_files = test_*.py *_test.py tests.py
addopts = --reuse-db
