[pytest]
# Indica el archivo de configuración de Django en tu proyecto
DJANGO_SETTINGS_MODULE = Django_6_crud.settings
# Indica los archivos que se considerarán como pruebas
python_files = tests.py test_*.py *_tests.py
