# Generated by Django 6.0.2 on 2026-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('parroquia', models.CharField(choices=[('Antonio Spinetti Dini', 'Antonio Spinetti Dini'), ('Arias', 'Arias'), ('Caracciolo Parra Pérez', 'Caracciolo Parra Pérez'), ('Domingo Peña', 'Domingo Peña'), ('El Llano', 'El Llano'), ('El Sagrario', 'El Sagrario'), ('Gonzalo Picón Febres', 'Gonzalo Picón Febres'), ('Jacinto Plaza', 'Jacinto Plaza'), ('Lasso de la Vega', 'Lasso de la Vega'), ('Juan Rodríguez Suárez', 'Juan Rodríguez Suárez'), ('Mariano Picón Salas', 'Mariano Picón Salas'), ('Milla', 'Milla'), ('Osuna Rodríguez', 'Osuna Rodríguez')], max_length=100)),
                ('fecha_registro', models.DateField()),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('retirado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tamano_cilindro', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=20, verbose_name='Tamaño de Cilindro')),
                ('visitado', models.BooleanField(default=False)),
                ('documentos_completos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
