# Generated by Django 6.0.2 on 2026-04-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_update_quiniela', models.BooleanField(default=False, verbose_name='Deshabilitar actualización de quiniela')),
                ('disable_registration', models.BooleanField(default=False, verbose_name='Deshabilitar nuevos registros en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
