# Generated by Django 6.0.2 on 2026-04-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='disable_update_quiniela',
            field=models.BooleanField(default=False, verbose_name='Deshabilitar actualización de quinielas'),
        ),
    ]
