# Generated by Django 6.0.2 on 2026-06-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ente_propietario', models.CharField(max_length=100, verbose_name='Ente propietario')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad_litros', models.CharField(max_length=100, verbose_name='Cantidad (Litros)')),
                ('motivo_uso', models.CharField(max_length=100, verbose_name='Motivo de uso')),
                ('autorizado_por', models.CharField(max_length=100, verbose_name='Autorizado por')),
                ('rec_entr_por', models.CharField(max_length=100, verbose_name='Recibido/Entregado por')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
        ),
    ]
