# Generated by Django 6.0.2 on 2026-05-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
