# Generated by Django 6.0.2 on 2026-05-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
    ]
